export const ActionTypes = {
  TRACKS_SET: 'TRACKS_SET',
  ADD_TODO: 'ADD_TODO',
  SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',
  TOGGLE_TODO: 'TOGGLE_TODO',
  ADD_TRACK: 'ADD_TRACK',
  SET_LOGIN_PENDING : 'SET_LOGIN_PENDING',
  SET_LOGIN_SUCCESS : 'SET_LOGIN_SUCCESS',
  SET_LOGIN_ERROR : 'SET_LOGIN_ERROR',
  LOGIN : 'LOGIN'
}
