export const ActionTypes = {
  SET_LOGIN_ERROR : 'SET_LOGIN_ERROR',
  MENU_SELECTED: 'MENU_SELECTED',
  SWITCH_LANGUAGE: 'SWITCH_LANGUAGE',
  SWITCH_THEME: 'SWITCH_THEME',
  CONFIGUATIONS: 'CONFIGUATIONS',


  STOCKSEARCH: 'STOCKSEARCH',
  ENQUIRYORDER: 'ENQUIRYORDER',
  CANELORDER: 'CANELORDER',
  CANCELSUBMIT: 'CANCELSUBMIT',
  
}
