export const ActionTypes = {
  SET_LOGIN_ERROR : 'SET_LOGIN_ERROR',
  MENU_SELECTED: 'MENU_SELECTED',
  SWITCH_LANGUAGE: 'SWITCH_LANGUAGE',
  SWITCH_THEME: 'SWITCH_THEME',
  CONFIGUATIONS: 'CONFIGUATIONS',
  TABCLICKEVENT: 'TABCLICKEVENT',

  STOCKSEARCH: 'STOCKSEARCH',
  ENQUIRYORDER: 'ENQUIRYORDER',
  ACCOUNTBALANCE:'ACCOUNTBALANCE',
  CASHTRANSHISTORY: 'CASHTRANSHISTORY',
  STOCKINFO: 'STOCKINFO',
  SET_ERROR: 'SET_ERROR',
  SET_AUTHEN_FAIL: 'SET_AUTHEN_FAIL',
  CANELORDER: 'CANELORDER',
  CANCELSUBMIT: 'CANCELSUBMIT',
  MODIFYSUBMIT: 'MODIFYSUBMIT',
  GETMODIFYDATA: 'GETMODIFYDATA',
  PAGINATION: 'PAGINATION',
  OPENPOPUP: 'OPENPOPUP',
  GETSTOCKINFO:'GETSTOCKINFO',
  ACCOUNTBALANCEINFO: 'ACCOUNTBALANCEINFO',
  ACCOUNTBALANCEBANKINFO: 'ACCOUNTBALANCEBANKINFO',
  OVERDUEDEBT: 'OVERDUEDEBT',
  UPCOMINGDEBT: 'UPCOMINGDEBT',
  GETCASHADVANCEHISTORY: 'GETCASHADVANCEHISTORY',
  QUERYSOLDORDERS:'QUERYSOLDORDERS',
  GETLOCALADVANCECREATION: 'GETLOCALADVANCECREATION',
  QUERYADVANCEPAYMENTINFO: 'QUERYADVANCEPAYMENTINFO',
  QUERYBANKINFO: 'QUERYBANKINFO',
  CALCULATEINTERSETAMT: 'CALCULATEINTERSETAMT',
  
  ENQUIRYCONFIRMORDER: 'ENQUIRYCONFIRMORDER',
  CONFIRMORDERSUBMIT: 'CONFIRMORDERSUBMIT',
  PORFOLIO: 'PORFOLIO',
  ENQUIRYORDERHISTORY:'ENQUIRYORDERHISTORY',
  ENQUIRYCASHTRANSACTION: 'ENQUIRYCASHTRANSACTION',
  ENQUIRYSTOCKSTATEMENT: 'ENQUIRYSTOCKSTATEMENT',
  CASHSTATEMENT:'CASHSTATEMENT',
  LOADWATCHLIST: 'LOADWATCHLIST',
  ADDSTOCK: "ADDSTOCK",
  REMOVESTOCK: "REMOVESTOCK",
  PROFILE: 'PROFILE',
  CHANGEPASSWORD: 'CHANGEPASSWORD',

  ODDLOTENQUIRY: 'ODDLOTENQUIRY',
  ODDLOTHISTORY :'ODDLOTHISTORY',
  ODDLOTSUBMIT: 'ODDLOTSUBMIT',
  CASHTRANSFER: 'CASHTRANSFER',
  CASHDATATABLE: 'CASHDATATABLE',
  MATRIXCARD: 'MATRIXCARD',
  MODIFYERROR: 'MODIFYERROR',
  MODIFYSUCCESS: 'MODIFYSUCCESS',
  ENTERORDER: 'ENTERORDER',
  GENENTERORDER: 'GENENTERORDER',
  NOTIFICATION: 'NOTIFICATION',
  FLASHPOPUP: 'FLASHPOPUP',
  MESSAGEBOX: 'MESSAGEBOX',
  ENQUIRYMARGINLOAN: 'ENQUIRYMARGINLOAN',
  AVAIBLEMARGINLIST: 'AVAIBLEMARGINLIST',
  BANKINFO:'BANKINFO',

  LOANREFUNDHISTORY:'LOANREFUNDHISTORY',
  LOCALADVANCE:'LOCALADVANCE',
  LOCALREFUND:'LOCALREFUND',
  LOANREFUNDSUBMIT:'LOANREFUNDSUBMIT',
  ADVANCESUBMIT:'ADVANCESUBMIT',
  LOANREFUNDDATA:'LOANREFUNDDATA',

  ENTITLEMENTRIGHTLIST: 'ENTITLEMENTRIGHTLIST',
  ENTITLEMENTADDITIONALSHARELIST: 'ENTITLEMENTADDITIONALSHARELIST',
  ENTITLEMENTHISTORYLIST: 'ENTITLEMENTHISTORYLIST',
  ENTITLEMENTSTOCKLIST: 'ENTITLEMENTSTOCKLIST',
  DYNAMICDATA: 'DYNAMICDATA',

  FUNDTRANSFER: 'FUNDTRANSFER',
  HKSCASHTRANHIS: 'HKSCASHTRANHIS',
  GENFUNDTRANSFER: 'GENFUNDTRANSFER',
  CANCELFUNDTRANSFER: 'CANCELFUNDTRANSFER',
  
  SAVELAYOUT: 'SAVELAYOUT',
  GETSAVEDCONTENTLAYOUT: 'GETSAVEDCONTENTLAYOUT',

  CHECKSESSION: 'CHECKSESSION',

  POPUP: 'POPUP',
  // Excel
  EXPORTGETCASHTRANSACTIONHISTORY: 'EXPORTGETCASHTRANSACTIONHISTORY',
  EXPORTORDERHISTORY: 'EXPORTORDERHISTORY',
  EXPORTCASHTRANSACTIONHISTORY: 'EXPORTCASHTRANSACTIONHISTORY',
  EXPORTTRANSACTIONHISTORY: 'EXPORTTRANSACTIONHISTORY',
  EXPORTORDERCONFIRM: 'EXPORTORDERCONFIRM',

  ///
  RELOADCUSTOM: 'RELOADCUSTOM',

  ///
  GETCAPTCHAIMAGE: 'GETCAPTCHAIMAGE',

  ///
  STOCKWATCHDATAUPDATE: 'STOCKWATCHDATAUPDATE'
}

export const Contants = {
  dateFormat: 'DD/MM/YYYY',
}
